name    'puppet-git'
version '0.0.1'
source  'https://github.com/atomaka/puppet-git'
author  'Andrew Tomaka'
license 'FIXME'
summary 'Puppet Git Module'
description 'Module to install Git using puppet'
project_page 'https://github.com/atomaka/puppet-git/'
dependency 'puppetlabs/apt', '>= 1.1.0'
